<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Order"
     targetNamespace="http://oracle.com/sca/soapservice/FiapRoupas/FluxoCompras/Order"
     xmlns:tns="http://oracle.com/sca/soapservice/FiapRoupas/FluxoCompras/Order"
     xmlns:inp1="http://www.example.org"
     xmlns:inp2="http://xmlns.oracle.com/singleString"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="../Schemas/modelo-canonico.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.oracle.com/singleString" schemaLocation="../Schemas/singleString.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="partIn" element="inp1:Order"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="partOut" element="inp1:Order"/>
    </wsdl:message>
    <wsdl:message name="faultMessage">
        <wsdl:part name="partFault" element="inp2:singleString"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
            <wsdl:fault name="executefault" message="tns:faultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
